/**
 * Seed Firestore with sample vocabulary data using Firebase Web SDK
 * 
 * Run with: npx ts-node --esm scripts/seed-web.ts
 */

import { initializeApp } from 'firebase/app';
import { getFirestore, collection, doc, setDoc, serverTimestamp } from 'firebase/firestore';
import * as dotenv from 'dotenv';

dotenv.config();

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Sample N5 vocabulary data
const N5_VOCABULARY = [
  {
    term: '食べる',
    reading: 'たべる',
    meaning: 'to eat',
    synonyms: ['eat', 'to consume'],
    readingSynonyms: ['taberu'],
    level: 'N5',
    order: 1,
    partOfSpeech: 'verb',
    exampleJapanese: '朝ごはんを食べる',
    exampleEnglish: 'I eat breakfast',
    tags: ['food', 'daily-life'],
  },
  {
    term: '飲む',
    reading: 'のむ',
    meaning: 'to drink',
    synonyms: ['drink'],
    readingSynonyms: ['nomu'],
    level: 'N5',
    order: 2,
    partOfSpeech: 'verb',
    exampleJapanese: '水を飲む',
    exampleEnglish: 'I drink water',
    tags: ['food', 'daily-life'],
  },
  {
    term: '行く',
    reading: 'いく',
    meaning: 'to go',
    synonyms: ['go'],
    readingSynonyms: ['iku'],
    level: 'N5',
    order: 3,
    partOfSpeech: 'verb',
    exampleJapanese: '学校に行く',
    exampleEnglish: 'I go to school',
    tags: ['movement'],
  },
  {
    term: '来る',
    reading: 'くる',
    meaning: 'to come',
    synonyms: ['come'],
    readingSynonyms: ['kuru'],
    level: 'N5',
    order: 4,
    partOfSpeech: 'verb',
    exampleJapanese: '友達が来る',
    exampleEnglish: 'A friend comes',
    tags: ['movement'],
  },
  {
    term: '見る',
    reading: 'みる',
    meaning: 'to see, to look, to watch',
    synonyms: ['see', 'look', 'watch'],
    readingSynonyms: ['miru'],
    level: 'N5',
    order: 5,
    partOfSpeech: 'verb',
    exampleJapanese: 'テレビを見る',
    exampleEnglish: 'I watch TV',
    tags: ['senses'],
  },
  {
    term: '聞く',
    reading: 'きく',
    meaning: 'to hear, to listen, to ask',
    synonyms: ['hear', 'listen', 'ask'],
    readingSynonyms: ['kiku'],
    level: 'N5',
    order: 6,
    partOfSpeech: 'verb',
    exampleJapanese: '音楽を聞く',
    exampleEnglish: 'I listen to music',
    tags: ['senses'],
  },
  {
    term: '読む',
    reading: 'よむ',
    meaning: 'to read',
    synonyms: ['read'],
    readingSynonyms: ['yomu'],
    level: 'N5',
    order: 7,
    partOfSpeech: 'verb',
    exampleJapanese: '本を読む',
    exampleEnglish: 'I read a book',
    tags: ['study'],
  },
  {
    term: '書く',
    reading: 'かく',
    meaning: 'to write',
    synonyms: ['write'],
    readingSynonyms: ['kaku'],
    level: 'N5',
    order: 8,
    partOfSpeech: 'verb',
    exampleJapanese: '手紙を書く',
    exampleEnglish: 'I write a letter',
    tags: ['study'],
  },
  {
    term: '話す',
    reading: 'はなす',
    meaning: 'to speak, to talk',
    synonyms: ['speak', 'talk'],
    readingSynonyms: ['hanasu'],
    level: 'N5',
    order: 9,
    partOfSpeech: 'verb',
    exampleJapanese: '日本語を話す',
    exampleEnglish: 'I speak Japanese',
    tags: ['communication'],
  },
  {
    term: '買う',
    reading: 'かう',
    meaning: 'to buy',
    synonyms: ['buy', 'purchase'],
    readingSynonyms: ['kau'],
    level: 'N5',
    order: 10,
    partOfSpeech: 'verb',
    exampleJapanese: '本を買う',
    exampleEnglish: 'I buy a book',
    tags: ['shopping'],
  },
  {
    term: '日本',
    reading: 'にほん',
    meaning: 'Japan',
    synonyms: ['Nippon'],
    readingSynonyms: ['nihon'],
    level: 'N5',
    order: 11,
    partOfSpeech: 'noun',
    exampleJapanese: '日本に住んでいます',
    exampleEnglish: 'I live in Japan',
    tags: ['country'],
  },
  {
    term: '人',
    reading: 'ひと',
    meaning: 'person, people',
    synonyms: ['person', 'people'],
    readingSynonyms: ['hito'],
    level: 'N5',
    order: 12,
    partOfSpeech: 'noun',
    exampleJapanese: 'あの人は誰ですか',
    exampleEnglish: 'Who is that person?',
    tags: ['people'],
  },
  {
    term: '水',
    reading: 'みず',
    meaning: 'water',
    synonyms: ['water'],
    readingSynonyms: ['mizu'],
    level: 'N5',
    order: 13,
    partOfSpeech: 'noun',
    exampleJapanese: '水をください',
    exampleEnglish: 'Please give me water',
    tags: ['food', 'nature'],
  },
  {
    term: '学校',
    reading: 'がっこう',
    meaning: 'school',
    synonyms: ['school'],
    readingSynonyms: ['gakkou'],
    level: 'N5',
    order: 14,
    partOfSpeech: 'noun',
    exampleJapanese: '学校は大きいです',
    exampleEnglish: 'The school is big',
    tags: ['education', 'place'],
  },
  {
    term: '友達',
    reading: 'ともだち',
    meaning: 'friend',
    synonyms: ['friend'],
    readingSynonyms: ['tomodachi'],
    level: 'N5',
    order: 15,
    partOfSpeech: 'noun',
    exampleJapanese: '友達と遊ぶ',
    exampleEnglish: 'I play with friends',
    tags: ['people'],
  },
  {
    term: '大きい',
    reading: 'おおきい',
    meaning: 'big, large',
    synonyms: ['big', 'large'],
    readingSynonyms: ['ookii'],
    level: 'N5',
    order: 16,
    partOfSpeech: 'adjective',
    exampleJapanese: '大きい犬',
    exampleEnglish: 'A big dog',
    tags: ['size'],
  },
  {
    term: '小さい',
    reading: 'ちいさい',
    meaning: 'small, little',
    synonyms: ['small', 'little'],
    readingSynonyms: ['chiisai'],
    level: 'N5',
    order: 17,
    partOfSpeech: 'adjective',
    exampleJapanese: '小さい猫',
    exampleEnglish: 'A small cat',
    tags: ['size'],
  },
  {
    term: '新しい',
    reading: 'あたらしい',
    meaning: 'new',
    synonyms: ['new', 'fresh'],
    readingSynonyms: ['atarashii'],
    level: 'N5',
    order: 18,
    partOfSpeech: 'adjective',
    exampleJapanese: '新しい本',
    exampleEnglish: 'A new book',
    tags: ['time'],
  },
  {
    term: 'いい',
    reading: 'いい',
    meaning: 'good, nice',
    synonyms: ['good', 'nice', 'fine'],
    readingSynonyms: ['ii', 'yoi'],
    level: 'N5',
    order: 19,
    partOfSpeech: 'adjective',
    exampleJapanese: 'いい天気',
    exampleEnglish: 'Good weather',
    tags: ['quality'],
  },
  {
    term: '今日',
    reading: 'きょう',
    meaning: 'today',
    synonyms: ['today'],
    readingSynonyms: ['kyou'],
    level: 'N5',
    order: 20,
    partOfSpeech: 'noun',
    exampleJapanese: '今日は何曜日ですか',
    exampleEnglish: 'What day is today?',
    tags: ['time'],
  },
  // Additional N5 vocabulary (21-50)
  {
    term: '明日',
    reading: 'あした',
    meaning: 'tomorrow',
    synonyms: ['tomorrow'],
    readingSynonyms: ['ashita'],
    level: 'N5',
    order: 21,
    partOfSpeech: 'noun',
    exampleJapanese: '明日また会いましょう',
    exampleEnglish: "Let's meet again tomorrow",
    tags: ['time'],
  },
  {
    term: '昨日',
    reading: 'きのう',
    meaning: 'yesterday',
    synonyms: ['yesterday'],
    readingSynonyms: ['kinou'],
    level: 'N5',
    order: 22,
    partOfSpeech: 'noun',
    exampleJapanese: '昨日は雨でした',
    exampleEnglish: 'It was rainy yesterday',
    tags: ['time'],
  },
  {
    term: '電車',
    reading: 'でんしゃ',
    meaning: 'train',
    synonyms: ['train', 'electric train'],
    readingSynonyms: ['densha'],
    level: 'N5',
    order: 23,
    partOfSpeech: 'noun',
    exampleJapanese: '電車で行きます',
    exampleEnglish: 'I go by train',
    tags: ['transport'],
  },
  {
    term: '駅',
    reading: 'えき',
    meaning: 'station',
    synonyms: ['station'],
    readingSynonyms: ['eki'],
    level: 'N5',
    order: 24,
    partOfSpeech: 'noun',
    exampleJapanese: '駅はどこですか',
    exampleEnglish: 'Where is the station?',
    tags: ['transport', 'place'],
  },
  {
    term: '家',
    reading: 'いえ',
    meaning: 'house, home',
    synonyms: ['house', 'home'],
    readingSynonyms: ['ie', 'uchi'],
    level: 'N5',
    order: 25,
    partOfSpeech: 'noun',
    exampleJapanese: '家に帰ります',
    exampleEnglish: 'I return home',
    tags: ['place'],
  },
  {
    term: '会社',
    reading: 'かいしゃ',
    meaning: 'company',
    synonyms: ['company', 'office'],
    readingSynonyms: ['kaisha'],
    level: 'N5',
    order: 26,
    partOfSpeech: 'noun',
    exampleJapanese: '会社で働いています',
    exampleEnglish: 'I work at a company',
    tags: ['work', 'place'],
  },
  {
    term: '仕事',
    reading: 'しごと',
    meaning: 'work, job',
    synonyms: ['work', 'job'],
    readingSynonyms: ['shigoto'],
    level: 'N5',
    order: 27,
    partOfSpeech: 'noun',
    exampleJapanese: '仕事が好きです',
    exampleEnglish: 'I like my job',
    tags: ['work'],
  },
  {
    term: '先生',
    reading: 'せんせい',
    meaning: 'teacher',
    synonyms: ['teacher', 'professor'],
    readingSynonyms: ['sensei'],
    level: 'N5',
    order: 28,
    partOfSpeech: 'noun',
    exampleJapanese: '先生に聞きます',
    exampleEnglish: 'I ask the teacher',
    tags: ['people', 'education'],
  },
  {
    term: '学生',
    reading: 'がくせい',
    meaning: 'student',
    synonyms: ['student'],
    readingSynonyms: ['gakusei'],
    level: 'N5',
    order: 29,
    partOfSpeech: 'noun',
    exampleJapanese: '私は学生です',
    exampleEnglish: 'I am a student',
    tags: ['people', 'education'],
  },
  {
    term: '時間',
    reading: 'じかん',
    meaning: 'time',
    synonyms: ['time', 'hour'],
    readingSynonyms: ['jikan'],
    level: 'N5',
    order: 30,
    partOfSpeech: 'noun',
    exampleJapanese: '時間がありません',
    exampleEnglish: 'I have no time',
    tags: ['time'],
  },
  {
    term: '毎日',
    reading: 'まいにち',
    meaning: 'every day',
    synonyms: ['every day', 'daily'],
    readingSynonyms: ['mainichi'],
    level: 'N5',
    order: 31,
    partOfSpeech: 'noun',
    exampleJapanese: '毎日勉強します',
    exampleEnglish: 'I study every day',
    tags: ['time'],
  },
  {
    term: '食べ物',
    reading: 'たべもの',
    meaning: 'food',
    synonyms: ['food'],
    readingSynonyms: ['tabemono'],
    level: 'N5',
    order: 32,
    partOfSpeech: 'noun',
    exampleJapanese: '日本の食べ物が好きです',
    exampleEnglish: 'I like Japanese food',
    tags: ['food'],
  },
  {
    term: '飲み物',
    reading: 'のみもの',
    meaning: 'drink, beverage',
    synonyms: ['drink', 'beverage'],
    readingSynonyms: ['nomimono'],
    level: 'N5',
    order: 33,
    partOfSpeech: 'noun',
    exampleJapanese: '飲み物はいかがですか',
    exampleEnglish: 'Would you like a drink?',
    tags: ['food'],
  },
  {
    term: '高い',
    reading: 'たかい',
    meaning: 'high, tall, expensive',
    synonyms: ['high', 'tall', 'expensive'],
    readingSynonyms: ['takai'],
    level: 'N5',
    order: 34,
    partOfSpeech: 'adjective',
    exampleJapanese: 'この本は高いです',
    exampleEnglish: 'This book is expensive',
    tags: ['size', 'price'],
  },
  {
    term: '安い',
    reading: 'やすい',
    meaning: 'cheap, inexpensive',
    synonyms: ['cheap', 'inexpensive'],
    readingSynonyms: ['yasui'],
    level: 'N5',
    order: 35,
    partOfSpeech: 'adjective',
    exampleJapanese: 'これは安いです',
    exampleEnglish: 'This is cheap',
    tags: ['price'],
  },
  {
    term: '早い',
    reading: 'はやい',
    meaning: 'early, fast',
    synonyms: ['early', 'fast', 'quick'],
    readingSynonyms: ['hayai'],
    level: 'N5',
    order: 36,
    partOfSpeech: 'adjective',
    exampleJapanese: '朝早く起きます',
    exampleEnglish: 'I wake up early in the morning',
    tags: ['time', 'speed'],
  },
  {
    term: '遅い',
    reading: 'おそい',
    meaning: 'late, slow',
    synonyms: ['late', 'slow'],
    readingSynonyms: ['osoi'],
    level: 'N5',
    order: 37,
    partOfSpeech: 'adjective',
    exampleJapanese: '遅くなってすみません',
    exampleEnglish: "Sorry I'm late",
    tags: ['time', 'speed'],
  },
  {
    term: '長い',
    reading: 'ながい',
    meaning: 'long',
    synonyms: ['long'],
    readingSynonyms: ['nagai'],
    level: 'N5',
    order: 38,
    partOfSpeech: 'adjective',
    exampleJapanese: '長い髪',
    exampleEnglish: 'Long hair',
    tags: ['size'],
  },
  {
    term: '短い',
    reading: 'みじかい',
    meaning: 'short',
    synonyms: ['short', 'brief'],
    readingSynonyms: ['mijikai'],
    level: 'N5',
    order: 39,
    partOfSpeech: 'adjective',
    exampleJapanese: '短い時間',
    exampleEnglish: 'A short time',
    tags: ['size'],
  },
  {
    term: '古い',
    reading: 'ふるい',
    meaning: 'old (things)',
    synonyms: ['old', 'ancient'],
    readingSynonyms: ['furui'],
    level: 'N5',
    order: 40,
    partOfSpeech: 'adjective',
    exampleJapanese: '古い建物',
    exampleEnglish: 'An old building',
    tags: ['time'],
  },
  {
    term: '作る',
    reading: 'つくる',
    meaning: 'to make, to create',
    synonyms: ['make', 'create', 'build'],
    readingSynonyms: ['tsukuru'],
    level: 'N5',
    order: 41,
    partOfSpeech: 'verb',
    exampleJapanese: '料理を作ります',
    exampleEnglish: 'I make food',
    tags: ['action'],
  },
  {
    term: '待つ',
    reading: 'まつ',
    meaning: 'to wait',
    synonyms: ['wait'],
    readingSynonyms: ['matsu'],
    level: 'N5',
    order: 42,
    partOfSpeech: 'verb',
    exampleJapanese: 'ちょっと待ってください',
    exampleEnglish: 'Please wait a moment',
    tags: ['action'],
  },
  {
    term: '会う',
    reading: 'あう',
    meaning: 'to meet',
    synonyms: ['meet', 'see'],
    readingSynonyms: ['au'],
    level: 'N5',
    order: 43,
    partOfSpeech: 'verb',
    exampleJapanese: '友達に会います',
    exampleEnglish: 'I meet a friend',
    tags: ['people', 'action'],
  },
  {
    term: '使う',
    reading: 'つかう',
    meaning: 'to use',
    synonyms: ['use'],
    readingSynonyms: ['tsukau'],
    level: 'N5',
    order: 44,
    partOfSpeech: 'verb',
    exampleJapanese: 'パソコンを使います',
    exampleEnglish: 'I use a computer',
    tags: ['action'],
  },
  {
    term: '泳ぐ',
    reading: 'およぐ',
    meaning: 'to swim',
    synonyms: ['swim'],
    readingSynonyms: ['oyogu'],
    level: 'N5',
    order: 45,
    partOfSpeech: 'verb',
    exampleJapanese: 'プールで泳ぎます',
    exampleEnglish: 'I swim in the pool',
    tags: ['sport'],
  },
  {
    term: '走る',
    reading: 'はしる',
    meaning: 'to run',
    synonyms: ['run'],
    readingSynonyms: ['hashiru'],
    level: 'N5',
    order: 46,
    partOfSpeech: 'verb',
    exampleJapanese: '公園で走ります',
    exampleEnglish: 'I run in the park',
    tags: ['sport', 'movement'],
  },
  {
    term: '歩く',
    reading: 'あるく',
    meaning: 'to walk',
    synonyms: ['walk'],
    readingSynonyms: ['aruku'],
    level: 'N5',
    order: 47,
    partOfSpeech: 'verb',
    exampleJapanese: '毎日歩きます',
    exampleEnglish: 'I walk every day',
    tags: ['movement'],
  },
  {
    term: '座る',
    reading: 'すわる',
    meaning: 'to sit',
    synonyms: ['sit'],
    readingSynonyms: ['suwaru'],
    level: 'N5',
    order: 48,
    partOfSpeech: 'verb',
    exampleJapanese: 'ここに座ってください',
    exampleEnglish: 'Please sit here',
    tags: ['action'],
  },
  {
    term: '立つ',
    reading: 'たつ',
    meaning: 'to stand',
    synonyms: ['stand'],
    readingSynonyms: ['tatsu'],
    level: 'N5',
    order: 49,
    partOfSpeech: 'verb',
    exampleJapanese: '立ってください',
    exampleEnglish: 'Please stand up',
    tags: ['action'],
  },
  {
    term: '寝る',
    reading: 'ねる',
    meaning: 'to sleep, to go to bed',
    synonyms: ['sleep', 'go to bed'],
    readingSynonyms: ['neru'],
    level: 'N5',
    order: 50,
    partOfSpeech: 'verb',
    exampleJapanese: '11時に寝ます',
    exampleEnglish: 'I go to bed at 11',
    tags: ['daily-life'],
  },
];

// Sample N5 grammar points
const N5_GRAMMAR = [
  {
    pattern: 'です',
    meaning: 'is, am, are (polite copula)',
    level: 'N5',
    order: 1,
    explanation: 'です is the polite form of the copula, used to link a subject to a noun or adjective.',
    formation: 'Noun + です\nな-adjective + です',
    examples: [
      { japanese: '私は学生です。', reading: 'わたしはがくせいです。', english: 'I am a student.' },
      { japanese: 'これは本です。', reading: 'これはほんです。', english: 'This is a book.' },
    ],
    tags: ['copula', 'polite'],
  },
  {
    pattern: 'ます',
    meaning: 'polite verb ending',
    level: 'N5',
    order: 2,
    explanation: 'ます is the polite verb ending used in formal situations.',
    formation: 'Verb stem + ます',
    examples: [
      { japanese: '食べます', reading: 'たべます', english: 'eat (polite)' },
      { japanese: '日本語を勉強します。', reading: 'にほんごをべんきょうします。', english: 'I study Japanese.' },
    ],
    tags: ['verb', 'polite'],
  },
  {
    pattern: 'は (topic marker)',
    meaning: 'as for, speaking of',
    level: 'N5',
    order: 3,
    explanation: 'は marks the topic of a sentence. Pronounced "wa" as a particle.',
    formation: 'Noun + は',
    examples: [
      { japanese: '私は日本人です。', reading: 'わたしはにほんじんです。', english: 'I am Japanese.' },
    ],
    tags: ['particle', 'topic'],
  },
  {
    pattern: 'を (object marker)',
    meaning: 'object marker',
    level: 'N5',
    order: 4,
    explanation: 'を marks the direct object of a verb.',
    formation: 'Noun + を + Verb',
    examples: [
      { japanese: '水を飲みます。', reading: 'みずをのみます。', english: 'I drink water.' },
    ],
    tags: ['particle', 'object'],
  },
  {
    pattern: 'に (location/time)',
    meaning: 'at, in, on, to',
    level: 'N5',
    order: 5,
    explanation: 'に indicates a specific point in time or destination.',
    formation: 'Time/Place + に',
    examples: [
      { japanese: '7時に起きます。', reading: 'しちじにおきます。', english: 'I wake up at 7.' },
    ],
    tags: ['particle', 'location', 'time'],
  },
  // Additional N5 grammar (6-10)
  {
    pattern: 'で (location of action)',
    meaning: 'at, in (where action happens)',
    level: 'N5',
    order: 6,
    explanation: 'で indicates the location where an action takes place, or the means/method used.',
    formation: 'Place + で + Verb',
    examples: [
      { japanese: '図書館で勉強します。', reading: 'としょかんでべんきょうします。', english: 'I study at the library.' },
      { japanese: '箸で食べます。', reading: 'はしでたべます。', english: 'I eat with chopsticks.' },
    ],
    tags: ['particle', 'location'],
  },
  {
    pattern: 'から (from)',
    meaning: 'from, because',
    level: 'N5',
    order: 7,
    explanation: 'から indicates a starting point (time/place) or reason (because).',
    formation: 'Time/Place + から',
    examples: [
      { japanese: '9時から働きます。', reading: 'くじからはたらきます。', english: 'I work from 9 o\'clock.' },
      { japanese: '日本から来ました。', reading: 'にほんからきました。', english: 'I came from Japan.' },
    ],
    tags: ['particle', 'time', 'location'],
  },
  {
    pattern: 'まで (until)',
    meaning: 'until, to, as far as',
    level: 'N5',
    order: 8,
    explanation: 'まで indicates an ending point in time or space.',
    formation: 'Time/Place + まで',
    examples: [
      { japanese: '5時まで働きます。', reading: 'ごじまではたらきます。', english: 'I work until 5 o\'clock.' },
      { japanese: '駅まで歩きます。', reading: 'えきまであるきます。', english: 'I walk to the station.' },
    ],
    tags: ['particle', 'time', 'location'],
  },
  {
    pattern: 'と (and/with)',
    meaning: 'and, with (person)',
    level: 'N5',
    order: 9,
    explanation: 'と connects nouns (and) or indicates doing something with someone.',
    formation: 'Noun + と + Noun / Person + と + Verb',
    examples: [
      { japanese: 'パンと牛乳を買います。', reading: 'パンとぎゅうにゅうをかいます。', english: 'I buy bread and milk.' },
      { japanese: '友達と遊びます。', reading: 'ともだちとあそびます。', english: 'I play with friends.' },
    ],
    tags: ['particle', 'connection'],
  },
  {
    pattern: 'が (subject marker)',
    meaning: 'subject marker',
    level: 'N5',
    order: 10,
    explanation: 'が marks the grammatical subject, often used for new information or emphasis.',
    formation: 'Noun + が',
    examples: [
      { japanese: '猫がいます。', reading: 'ねこがいます。', english: 'There is a cat.' },
      { japanese: '何が好きですか。', reading: 'なにがすきですか。', english: 'What do you like?' },
    ],
    tags: ['particle', 'subject'],
  },
];

async function seedVocabulary() {
  console.log('Seeding vocabulary data...');
  
  for (let i = 0; i < N5_VOCABULARY.length; i++) {
    const vocab = N5_VOCABULARY[i];
    const docRef = doc(collection(db, 'vocabularies'));
    await setDoc(docRef, {
      ...vocab,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
    console.log(`  [${i + 1}/${N5_VOCABULARY.length}] Added: ${vocab.term}`);
  }
  
  console.log(`✅ Seeded ${N5_VOCABULARY.length} vocabulary items`);
}

async function seedGrammar() {
  console.log('Seeding grammar data...');
  
  for (let i = 0; i < N5_GRAMMAR.length; i++) {
    const grammar = N5_GRAMMAR[i];
    const docRef = doc(collection(db, 'grammarPoints'));
    await setDoc(docRef, {
      ...grammar,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
    console.log(`  [${i + 1}/${N5_GRAMMAR.length}] Added: ${grammar.pattern}`);
  }
  
  console.log(`✅ Seeded ${N5_GRAMMAR.length} grammar points`);
}

async function main() {
  console.log('🌱 Starting Firestore seed...\n');
  console.log(`Project: ${firebaseConfig.projectId}\n`);
  
  try {
    await seedVocabulary();
    console.log('');
    await seedGrammar();
    console.log('\n🎉 Seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
}

main();

