/**
 * Seed Firestore with sample vocabulary data
 * 
 * Run with: npx ts-node scripts/seed-firestore.ts
 * 
 * Note: Requires Firebase Admin SDK credentials.
 * Set GOOGLE_APPLICATION_CREDENTIALS env var to your service account key path.
 */

import * as admin from 'firebase-admin';

// Initialize Firebase Admin
admin.initializeApp({
  credential: admin.credential.applicationDefault(),
});

const db = admin.firestore();

// Sample N5 vocabulary data
const N5_VOCABULARY = [
  {
    term: '食べる',
    reading: 'たべる',
    meaning: 'to eat',
    synonyms: ['eat', 'to consume'],
    readingSynonyms: ['taberu'],
    jlptLevel: 'N5',
    frequencyRank: 1,
    partOfSpeech: 'verb',
    exampleJapanese: '朝ごはんを食べる',
    exampleEnglish: 'I eat breakfast',
    tags: ['food', 'daily-life'],
  },
  {
    term: '飲む',
    reading: 'のむ',
    meaning: 'to drink',
    synonyms: ['drink', 'to consume liquid'],
    readingSynonyms: ['nomu'],
    jlptLevel: 'N5',
    frequencyRank: 2,
    partOfSpeech: 'verb',
    exampleJapanese: '水を飲む',
    exampleEnglish: 'I drink water',
    tags: ['food', 'daily-life'],
  },
  {
    term: '行く',
    reading: 'いく',
    meaning: 'to go',
    synonyms: ['go', 'to travel'],
    readingSynonyms: ['iku'],
    jlptLevel: 'N5',
    frequencyRank: 3,
    partOfSpeech: 'verb',
    exampleJapanese: '学校に行く',
    exampleEnglish: 'I go to school',
    tags: ['movement', 'daily-life'],
  },
  {
    term: '来る',
    reading: 'くる',
    meaning: 'to come',
    synonyms: ['come', 'to arrive'],
    readingSynonyms: ['kuru'],
    jlptLevel: 'N5',
    frequencyRank: 4,
    partOfSpeech: 'verb',
    exampleJapanese: '友達が来る',
    exampleEnglish: 'A friend comes',
    tags: ['movement', 'daily-life'],
  },
  {
    term: '見る',
    reading: 'みる',
    meaning: 'to see, to look, to watch',
    synonyms: ['see', 'look', 'watch', 'to view'],
    readingSynonyms: ['miru'],
    jlptLevel: 'N5',
    frequencyRank: 5,
    partOfSpeech: 'verb',
    exampleJapanese: 'テレビを見る',
    exampleEnglish: 'I watch TV',
    tags: ['senses', 'daily-life'],
  },
  {
    term: '聞く',
    reading: 'きく',
    meaning: 'to hear, to listen, to ask',
    synonyms: ['hear', 'listen', 'ask'],
    readingSynonyms: ['kiku'],
    jlptLevel: 'N5',
    frequencyRank: 6,
    partOfSpeech: 'verb',
    exampleJapanese: '音楽を聞く',
    exampleEnglish: 'I listen to music',
    tags: ['senses', 'daily-life'],
  },
  {
    term: '読む',
    reading: 'よむ',
    meaning: 'to read',
    synonyms: ['read'],
    readingSynonyms: ['yomu'],
    jlptLevel: 'N5',
    frequencyRank: 7,
    partOfSpeech: 'verb',
    exampleJapanese: '本を読む',
    exampleEnglish: 'I read a book',
    tags: ['study', 'daily-life'],
  },
  {
    term: '書く',
    reading: 'かく',
    meaning: 'to write',
    synonyms: ['write'],
    readingSynonyms: ['kaku'],
    jlptLevel: 'N5',
    frequencyRank: 8,
    partOfSpeech: 'verb',
    exampleJapanese: '手紙を書く',
    exampleEnglish: 'I write a letter',
    tags: ['study', 'daily-life'],
  },
  {
    term: '話す',
    reading: 'はなす',
    meaning: 'to speak, to talk',
    synonyms: ['speak', 'talk', 'to converse'],
    readingSynonyms: ['hanasu'],
    jlptLevel: 'N5',
    frequencyRank: 9,
    partOfSpeech: 'verb',
    exampleJapanese: '日本語を話す',
    exampleEnglish: 'I speak Japanese',
    tags: ['communication', 'daily-life'],
  },
  {
    term: '買う',
    reading: 'かう',
    meaning: 'to buy',
    synonyms: ['buy', 'purchase'],
    readingSynonyms: ['kau'],
    jlptLevel: 'N5',
    frequencyRank: 10,
    partOfSpeech: 'verb',
    exampleJapanese: '本を買う',
    exampleEnglish: 'I buy a book',
    tags: ['shopping', 'daily-life'],
  },
  // Nouns
  {
    term: '日本',
    reading: 'にほん',
    meaning: 'Japan',
    synonyms: ['Nippon'],
    readingSynonyms: ['nihon', 'nippon'],
    jlptLevel: 'N5',
    frequencyRank: 11,
    partOfSpeech: 'noun',
    exampleJapanese: '日本に住んでいます',
    exampleEnglish: 'I live in Japan',
    tags: ['country', 'place'],
  },
  {
    term: '人',
    reading: 'ひと',
    meaning: 'person, people',
    synonyms: ['person', 'people', 'human'],
    readingSynonyms: ['hito'],
    jlptLevel: 'N5',
    frequencyRank: 12,
    partOfSpeech: 'noun',
    exampleJapanese: 'あの人は誰ですか',
    exampleEnglish: 'Who is that person?',
    tags: ['people'],
  },
  {
    term: '水',
    reading: 'みず',
    meaning: 'water',
    synonyms: ['water'],
    readingSynonyms: ['mizu'],
    jlptLevel: 'N5',
    frequencyRank: 13,
    partOfSpeech: 'noun',
    exampleJapanese: '水をください',
    exampleEnglish: 'Please give me water',
    tags: ['food', 'nature'],
  },
  {
    term: '学校',
    reading: 'がっこう',
    meaning: 'school',
    synonyms: ['school'],
    readingSynonyms: ['gakkou'],
    jlptLevel: 'N5',
    frequencyRank: 14,
    partOfSpeech: 'noun',
    exampleJapanese: '学校は大きいです',
    exampleEnglish: 'The school is big',
    tags: ['education', 'place'],
  },
  {
    term: '友達',
    reading: 'ともだち',
    meaning: 'friend',
    synonyms: ['friend', 'pal'],
    readingSynonyms: ['tomodachi'],
    jlptLevel: 'N5',
    frequencyRank: 15,
    partOfSpeech: 'noun',
    exampleJapanese: '友達と遊ぶ',
    exampleEnglish: 'I play with friends',
    tags: ['people', 'relationship'],
  },
  // Adjectives
  {
    term: '大きい',
    reading: 'おおきい',
    meaning: 'big, large',
    synonyms: ['big', 'large', 'great'],
    readingSynonyms: ['ookii'],
    jlptLevel: 'N5',
    frequencyRank: 16,
    partOfSpeech: 'adjective',
    exampleJapanese: '大きい犬',
    exampleEnglish: 'A big dog',
    tags: ['size', 'description'],
  },
  {
    term: '小さい',
    reading: 'ちいさい',
    meaning: 'small, little',
    synonyms: ['small', 'little', 'tiny'],
    readingSynonyms: ['chiisai'],
    jlptLevel: 'N5',
    frequencyRank: 17,
    partOfSpeech: 'adjective',
    exampleJapanese: '小さい猫',
    exampleEnglish: 'A small cat',
    tags: ['size', 'description'],
  },
  {
    term: '新しい',
    reading: 'あたらしい',
    meaning: 'new',
    synonyms: ['new', 'fresh'],
    readingSynonyms: ['atarashii'],
    jlptLevel: 'N5',
    frequencyRank: 18,
    partOfSpeech: 'adjective',
    exampleJapanese: '新しい本',
    exampleEnglish: 'A new book',
    tags: ['time', 'description'],
  },
  {
    term: '古い',
    reading: 'ふるい',
    meaning: 'old (things)',
    synonyms: ['old', 'ancient'],
    readingSynonyms: ['furui'],
    jlptLevel: 'N5',
    frequencyRank: 19,
    partOfSpeech: 'adjective',
    exampleJapanese: '古い家',
    exampleEnglish: 'An old house',
    tags: ['time', 'description'],
  },
  {
    term: 'いい',
    reading: 'いい',
    meaning: 'good, nice',
    synonyms: ['good', 'nice', 'fine', 'okay'],
    readingSynonyms: ['ii', 'yoi'],
    jlptLevel: 'N5',
    frequencyRank: 20,
    partOfSpeech: 'adjective',
    exampleJapanese: 'いい天気',
    exampleEnglish: 'Good weather',
    tags: ['quality', 'description'],
  },
  // More common N5 vocabulary
  {
    term: '時間',
    reading: 'じかん',
    meaning: 'time, hour',
    synonyms: ['time', 'hour'],
    readingSynonyms: ['jikan'],
    jlptLevel: 'N5',
    frequencyRank: 21,
    partOfSpeech: 'noun',
    exampleJapanese: '時間がありません',
    exampleEnglish: 'I don\'t have time',
    tags: ['time'],
  },
  {
    term: '今日',
    reading: 'きょう',
    meaning: 'today',
    synonyms: ['today'],
    readingSynonyms: ['kyou'],
    jlptLevel: 'N5',
    frequencyRank: 22,
    partOfSpeech: 'noun',
    exampleJapanese: '今日は何曜日ですか',
    exampleEnglish: 'What day is today?',
    tags: ['time', 'day'],
  },
  {
    term: '明日',
    reading: 'あした',
    meaning: 'tomorrow',
    synonyms: ['tomorrow'],
    readingSynonyms: ['ashita'],
    jlptLevel: 'N5',
    frequencyRank: 23,
    partOfSpeech: 'noun',
    exampleJapanese: '明日会いましょう',
    exampleEnglish: 'Let\'s meet tomorrow',
    tags: ['time', 'day'],
  },
  {
    term: '昨日',
    reading: 'きのう',
    meaning: 'yesterday',
    synonyms: ['yesterday'],
    readingSynonyms: ['kinou'],
    jlptLevel: 'N5',
    frequencyRank: 24,
    partOfSpeech: 'noun',
    exampleJapanese: '昨日映画を見ました',
    exampleEnglish: 'I watched a movie yesterday',
    tags: ['time', 'day'],
  },
  {
    term: '毎日',
    reading: 'まいにち',
    meaning: 'every day',
    synonyms: ['every day', 'daily'],
    readingSynonyms: ['mainichi'],
    jlptLevel: 'N5',
    frequencyRank: 25,
    partOfSpeech: 'noun',
    exampleJapanese: '毎日日本語を勉強します',
    exampleEnglish: 'I study Japanese every day',
    tags: ['time', 'frequency'],
  },
  {
    term: '電車',
    reading: 'でんしゃ',
    meaning: 'train',
    synonyms: ['train', 'electric train'],
    readingSynonyms: ['densha'],
    jlptLevel: 'N5',
    frequencyRank: 26,
    partOfSpeech: 'noun',
    exampleJapanese: '電車で会社に行きます',
    exampleEnglish: 'I go to the office by train',
    tags: ['transport', 'travel'],
  },
  {
    term: '駅',
    reading: 'えき',
    meaning: 'station',
    synonyms: ['station'],
    readingSynonyms: ['eki'],
    jlptLevel: 'N5',
    frequencyRank: 27,
    partOfSpeech: 'noun',
    exampleJapanese: '駅はどこですか',
    exampleEnglish: 'Where is the station?',
    tags: ['transport', 'place'],
  },
  {
    term: '会社',
    reading: 'かいしゃ',
    meaning: 'company, office',
    synonyms: ['company', 'office', 'corporation'],
    readingSynonyms: ['kaisha'],
    jlptLevel: 'N5',
    frequencyRank: 28,
    partOfSpeech: 'noun',
    exampleJapanese: '会社で働いています',
    exampleEnglish: 'I work at a company',
    tags: ['work', 'place'],
  },
  {
    term: '仕事',
    reading: 'しごと',
    meaning: 'work, job',
    synonyms: ['work', 'job', 'occupation'],
    readingSynonyms: ['shigoto'],
    jlptLevel: 'N5',
    frequencyRank: 29,
    partOfSpeech: 'noun',
    exampleJapanese: '仕事は何ですか',
    exampleEnglish: 'What is your job?',
    tags: ['work'],
  },
  {
    term: '先生',
    reading: 'せんせい',
    meaning: 'teacher',
    synonyms: ['teacher', 'sensei', 'master'],
    readingSynonyms: ['sensei'],
    jlptLevel: 'N5',
    frequencyRank: 30,
    partOfSpeech: 'noun',
    exampleJapanese: '先生は優しいです',
    exampleEnglish: 'The teacher is kind',
    tags: ['people', 'education'],
  },
  {
    term: '学生',
    reading: 'がくせい',
    meaning: 'student',
    synonyms: ['student'],
    readingSynonyms: ['gakusei'],
    jlptLevel: 'N5',
    frequencyRank: 31,
    partOfSpeech: 'noun',
    exampleJapanese: '私は大学生です',
    exampleEnglish: 'I am a university student',
    tags: ['people', 'education'],
  },
  {
    term: '映画',
    reading: 'えいが',
    meaning: 'movie, film',
    synonyms: ['movie', 'film'],
    readingSynonyms: ['eiga'],
    jlptLevel: 'N5',
    frequencyRank: 32,
    partOfSpeech: 'noun',
    exampleJapanese: '映画を見に行きます',
    exampleEnglish: 'I go to see a movie',
    tags: ['entertainment', 'hobby'],
  },
  {
    term: '音楽',
    reading: 'おんがく',
    meaning: 'music',
    synonyms: ['music'],
    readingSynonyms: ['ongaku'],
    jlptLevel: 'N5',
    frequencyRank: 33,
    partOfSpeech: 'noun',
    exampleJapanese: '音楽が好きです',
    exampleEnglish: 'I like music',
    tags: ['entertainment', 'hobby'],
  },
  {
    term: '天気',
    reading: 'てんき',
    meaning: 'weather',
    synonyms: ['weather'],
    readingSynonyms: ['tenki'],
    jlptLevel: 'N5',
    frequencyRank: 34,
    partOfSpeech: 'noun',
    exampleJapanese: '今日の天気は晴れです',
    exampleEnglish: 'Today\'s weather is sunny',
    tags: ['nature', 'weather'],
  },
  {
    term: '雨',
    reading: 'あめ',
    meaning: 'rain',
    synonyms: ['rain'],
    readingSynonyms: ['ame'],
    jlptLevel: 'N5',
    frequencyRank: 35,
    partOfSpeech: 'noun',
    exampleJapanese: '雨が降っています',
    exampleEnglish: 'It is raining',
    tags: ['nature', 'weather'],
  },
  // More verbs
  {
    term: '勉強する',
    reading: 'べんきょうする',
    meaning: 'to study',
    synonyms: ['study', 'to learn'],
    readingSynonyms: ['benkyou suru'],
    jlptLevel: 'N5',
    frequencyRank: 36,
    partOfSpeech: 'verb',
    exampleJapanese: '毎日勉強します',
    exampleEnglish: 'I study every day',
    tags: ['education', 'daily-life'],
  },
  {
    term: '分かる',
    reading: 'わかる',
    meaning: 'to understand',
    synonyms: ['understand', 'to know'],
    readingSynonyms: ['wakaru'],
    jlptLevel: 'N5',
    frequencyRank: 37,
    partOfSpeech: 'verb',
    exampleJapanese: '日本語が分かりますか',
    exampleEnglish: 'Do you understand Japanese?',
    tags: ['communication'],
  },
  {
    term: '作る',
    reading: 'つくる',
    meaning: 'to make',
    synonyms: ['make', 'create', 'build'],
    readingSynonyms: ['tsukuru'],
    jlptLevel: 'N5',
    frequencyRank: 38,
    partOfSpeech: 'verb',
    exampleJapanese: '料理を作ります',
    exampleEnglish: 'I make food',
    tags: ['daily-life'],
  },
  {
    term: '待つ',
    reading: 'まつ',
    meaning: 'to wait',
    synonyms: ['wait'],
    readingSynonyms: ['matsu'],
    jlptLevel: 'N5',
    frequencyRank: 39,
    partOfSpeech: 'verb',
    exampleJapanese: 'ここで待ってください',
    exampleEnglish: 'Please wait here',
    tags: ['daily-life'],
  },
  {
    term: '使う',
    reading: 'つかう',
    meaning: 'to use',
    synonyms: ['use'],
    readingSynonyms: ['tsukau'],
    jlptLevel: 'N5',
    frequencyRank: 40,
    partOfSpeech: 'verb',
    exampleJapanese: '箸を使います',
    exampleEnglish: 'I use chopsticks',
    tags: ['daily-life'],
  },
  // More adjectives
  {
    term: '高い',
    reading: 'たかい',
    meaning: 'high, expensive',
    synonyms: ['high', 'expensive', 'tall'],
    readingSynonyms: ['takai'],
    jlptLevel: 'N5',
    frequencyRank: 41,
    partOfSpeech: 'adjective',
    exampleJapanese: 'この山は高いです',
    exampleEnglish: 'This mountain is high',
    tags: ['size', 'price'],
  },
  {
    term: '安い',
    reading: 'やすい',
    meaning: 'cheap, inexpensive',
    synonyms: ['cheap', 'inexpensive'],
    readingSynonyms: ['yasui'],
    jlptLevel: 'N5',
    frequencyRank: 42,
    partOfSpeech: 'adjective',
    exampleJapanese: 'このレストランは安いです',
    exampleEnglish: 'This restaurant is cheap',
    tags: ['price'],
  },
  {
    term: '暑い',
    reading: 'あつい',
    meaning: 'hot (weather)',
    synonyms: ['hot'],
    readingSynonyms: ['atsui'],
    jlptLevel: 'N5',
    frequencyRank: 43,
    partOfSpeech: 'adjective',
    exampleJapanese: '今日は暑いです',
    exampleEnglish: 'Today is hot',
    tags: ['weather', 'temperature'],
  },
  {
    term: '寒い',
    reading: 'さむい',
    meaning: 'cold (weather)',
    synonyms: ['cold'],
    readingSynonyms: ['samui'],
    jlptLevel: 'N5',
    frequencyRank: 44,
    partOfSpeech: 'adjective',
    exampleJapanese: '冬は寒いです',
    exampleEnglish: 'Winter is cold',
    tags: ['weather', 'temperature'],
  },
  {
    term: '美味しい',
    reading: 'おいしい',
    meaning: 'delicious',
    synonyms: ['delicious', 'tasty', 'yummy'],
    readingSynonyms: ['oishii'],
    jlptLevel: 'N5',
    frequencyRank: 45,
    partOfSpeech: 'adjective',
    exampleJapanese: 'このラーメンは美味しいです',
    exampleEnglish: 'This ramen is delicious',
    tags: ['food', 'taste'],
  },
  {
    term: '楽しい',
    reading: 'たのしい',
    meaning: 'fun, enjoyable',
    synonyms: ['fun', 'enjoyable', 'pleasant'],
    readingSynonyms: ['tanoshii'],
    jlptLevel: 'N5',
    frequencyRank: 46,
    partOfSpeech: 'adjective',
    exampleJapanese: '旅行は楽しいです',
    exampleEnglish: 'Traveling is fun',
    tags: ['emotion', 'feeling'],
  },
  {
    term: '難しい',
    reading: 'むずかしい',
    meaning: 'difficult',
    synonyms: ['difficult', 'hard'],
    readingSynonyms: ['muzukashii'],
    jlptLevel: 'N5',
    frequencyRank: 47,
    partOfSpeech: 'adjective',
    exampleJapanese: '日本語は難しいです',
    exampleEnglish: 'Japanese is difficult',
    tags: ['difficulty'],
  },
  {
    term: '易しい',
    reading: 'やさしい',
    meaning: 'easy',
    synonyms: ['easy', 'simple'],
    readingSynonyms: ['yasashii'],
    jlptLevel: 'N5',
    frequencyRank: 48,
    partOfSpeech: 'adjective',
    exampleJapanese: 'この問題は易しいです',
    exampleEnglish: 'This problem is easy',
    tags: ['difficulty'],
  },
  {
    term: '忙しい',
    reading: 'いそがしい',
    meaning: 'busy',
    synonyms: ['busy'],
    readingSynonyms: ['isogashii'],
    jlptLevel: 'N5',
    frequencyRank: 49,
    partOfSpeech: 'adjective',
    exampleJapanese: '今週は忙しいです',
    exampleEnglish: 'This week is busy',
    tags: ['work', 'time'],
  },
  {
    term: '元気',
    reading: 'げんき',
    meaning: 'healthy, energetic',
    synonyms: ['healthy', 'energetic', 'well'],
    readingSynonyms: ['genki'],
    jlptLevel: 'N5',
    frequencyRank: 50,
    partOfSpeech: 'na-adjective',
    exampleJapanese: 'お元気ですか',
    exampleEnglish: 'How are you?',
    tags: ['health', 'greeting'],
  },
  // Family
  { term: '家族', reading: 'かぞく', meaning: 'family', synonyms: ['family'], readingSynonyms: ['kazoku'], jlptLevel: 'N5', frequencyRank: 51, partOfSpeech: 'noun', exampleJapanese: '家族と住んでいます', exampleEnglish: 'I live with my family', tags: ['family'] },
  { term: 'お父さん', reading: 'おとうさん', meaning: 'father', synonyms: ['father', 'dad'], readingSynonyms: ['otousan'], jlptLevel: 'N5', frequencyRank: 52, partOfSpeech: 'noun', exampleJapanese: 'お父さんはどこですか', exampleEnglish: 'Where is your father?', tags: ['family'] },
  { term: 'お母さん', reading: 'おかあさん', meaning: 'mother', synonyms: ['mother', 'mom'], readingSynonyms: ['okaasan'], jlptLevel: 'N5', frequencyRank: 53, partOfSpeech: 'noun', exampleJapanese: 'お母さんが好きです', exampleEnglish: 'I love my mother', tags: ['family'] },
  { term: 'お兄さん', reading: 'おにいさん', meaning: 'older brother', synonyms: ['older brother', 'big brother'], readingSynonyms: ['oniisan'], jlptLevel: 'N5', frequencyRank: 54, partOfSpeech: 'noun', exampleJapanese: 'お兄さんは学生です', exampleEnglish: 'My older brother is a student', tags: ['family'] },
  { term: 'お姉さん', reading: 'おねえさん', meaning: 'older sister', synonyms: ['older sister', 'big sister'], readingSynonyms: ['oneesan'], jlptLevel: 'N5', frequencyRank: 55, partOfSpeech: 'noun', exampleJapanese: 'お姉さんは優しいです', exampleEnglish: 'My older sister is kind', tags: ['family'] },
  // Body
  { term: '目', reading: 'め', meaning: 'eye', synonyms: ['eye', 'eyes'], readingSynonyms: ['me'], jlptLevel: 'N5', frequencyRank: 56, partOfSpeech: 'noun', exampleJapanese: '目が大きいです', exampleEnglish: 'The eyes are big', tags: ['body'] },
  { term: '耳', reading: 'みみ', meaning: 'ear', synonyms: ['ear', 'ears'], readingSynonyms: ['mimi'], jlptLevel: 'N5', frequencyRank: 57, partOfSpeech: 'noun', exampleJapanese: '耳が聞こえません', exampleEnglish: 'I can\'t hear', tags: ['body'] },
  { term: '手', reading: 'て', meaning: 'hand', synonyms: ['hand', 'hands'], readingSynonyms: ['te'], jlptLevel: 'N5', frequencyRank: 58, partOfSpeech: 'noun', exampleJapanese: '手を洗います', exampleEnglish: 'I wash my hands', tags: ['body'] },
  { term: '足', reading: 'あし', meaning: 'foot, leg', synonyms: ['foot', 'leg'], readingSynonyms: ['ashi'], jlptLevel: 'N5', frequencyRank: 59, partOfSpeech: 'noun', exampleJapanese: '足が痛いです', exampleEnglish: 'My leg hurts', tags: ['body'] },
  // Colors
  { term: '赤い', reading: 'あかい', meaning: 'red', synonyms: ['red'], readingSynonyms: ['akai'], jlptLevel: 'N5', frequencyRank: 60, partOfSpeech: 'adjective', exampleJapanese: '赤い車', exampleEnglish: 'A red car', tags: ['color'] },
  { term: '青い', reading: 'あおい', meaning: 'blue', synonyms: ['blue'], readingSynonyms: ['aoi'], jlptLevel: 'N5', frequencyRank: 61, partOfSpeech: 'adjective', exampleJapanese: '青い空', exampleEnglish: 'A blue sky', tags: ['color'] },
  { term: '白い', reading: 'しろい', meaning: 'white', synonyms: ['white'], readingSynonyms: ['shiroi'], jlptLevel: 'N5', frequencyRank: 62, partOfSpeech: 'adjective', exampleJapanese: '白い猫', exampleEnglish: 'A white cat', tags: ['color'] },
  { term: '黒い', reading: 'くろい', meaning: 'black', synonyms: ['black'], readingSynonyms: ['kuroi'], jlptLevel: 'N5', frequencyRank: 63, partOfSpeech: 'adjective', exampleJapanese: '黒い犬', exampleEnglish: 'A black dog', tags: ['color'] },
  // Food
  { term: 'ご飯', reading: 'ごはん', meaning: 'rice, meal', synonyms: ['rice', 'meal', 'cooked rice'], readingSynonyms: ['gohan'], jlptLevel: 'N5', frequencyRank: 64, partOfSpeech: 'noun', exampleJapanese: 'ご飯を食べます', exampleEnglish: 'I eat rice', tags: ['food'] },
  { term: 'パン', reading: 'ぱん', meaning: 'bread', synonyms: ['bread'], readingSynonyms: ['pan'], jlptLevel: 'N5', frequencyRank: 65, partOfSpeech: 'noun', exampleJapanese: 'パンを食べます', exampleEnglish: 'I eat bread', tags: ['food'] },
  { term: '肉', reading: 'にく', meaning: 'meat', synonyms: ['meat'], readingSynonyms: ['niku'], jlptLevel: 'N5', frequencyRank: 66, partOfSpeech: 'noun', exampleJapanese: '肉が好きです', exampleEnglish: 'I like meat', tags: ['food'] },
  { term: '魚', reading: 'さかな', meaning: 'fish', synonyms: ['fish'], readingSynonyms: ['sakana'], jlptLevel: 'N5', frequencyRank: 67, partOfSpeech: 'noun', exampleJapanese: '魚を食べます', exampleEnglish: 'I eat fish', tags: ['food'] },
  { term: 'コーヒー', reading: 'こーひー', meaning: 'coffee', synonyms: ['coffee'], readingSynonyms: ['koohii'], jlptLevel: 'N5', frequencyRank: 68, partOfSpeech: 'noun', exampleJapanese: 'コーヒーを飲みます', exampleEnglish: 'I drink coffee', tags: ['food', 'drink'] },
  // Verbs
  { term: '起きる', reading: 'おきる', meaning: 'to wake up, to get up', synonyms: ['wake up', 'get up'], readingSynonyms: ['okiru'], jlptLevel: 'N5', frequencyRank: 69, partOfSpeech: 'verb', exampleJapanese: '7時に起きます', exampleEnglish: 'I wake up at 7', tags: ['daily-life'] },
  { term: '寝る', reading: 'ねる', meaning: 'to sleep, to go to bed', synonyms: ['sleep', 'go to bed'], readingSynonyms: ['neru'], jlptLevel: 'N5', frequencyRank: 70, partOfSpeech: 'verb', exampleJapanese: '11時に寝ます', exampleEnglish: 'I go to bed at 11', tags: ['daily-life'] },
  { term: '帰る', reading: 'かえる', meaning: 'to return, to go home', synonyms: ['return', 'go home', 'come back'], readingSynonyms: ['kaeru'], jlptLevel: 'N5', frequencyRank: 71, partOfSpeech: 'verb', exampleJapanese: '家に帰ります', exampleEnglish: 'I go home', tags: ['movement', 'daily-life'] },
  { term: '入る', reading: 'はいる', meaning: 'to enter', synonyms: ['enter', 'go in', 'come in'], readingSynonyms: ['hairu'], jlptLevel: 'N5', frequencyRank: 72, partOfSpeech: 'verb', exampleJapanese: '部屋に入ります', exampleEnglish: 'I enter the room', tags: ['movement'] },
  { term: '出る', reading: 'でる', meaning: 'to leave, to exit', synonyms: ['leave', 'exit', 'go out'], readingSynonyms: ['deru'], jlptLevel: 'N5', frequencyRank: 73, partOfSpeech: 'verb', exampleJapanese: '家を出ます', exampleEnglish: 'I leave the house', tags: ['movement'] },
  { term: '会う', reading: 'あう', meaning: 'to meet', synonyms: ['meet', 'see (someone)'], readingSynonyms: ['au'], jlptLevel: 'N5', frequencyRank: 74, partOfSpeech: 'verb', exampleJapanese: '友達に会います', exampleEnglish: 'I meet my friend', tags: ['social', 'daily-life'] },
  { term: '住む', reading: 'すむ', meaning: 'to live, to reside', synonyms: ['live', 'reside'], readingSynonyms: ['sumu'], jlptLevel: 'N5', frequencyRank: 75, partOfSpeech: 'verb', exampleJapanese: '東京に住んでいます', exampleEnglish: 'I live in Tokyo', tags: ['daily-life'] },
  { term: '働く', reading: 'はたらく', meaning: 'to work', synonyms: ['work'], readingSynonyms: ['hataraku'], jlptLevel: 'N5', frequencyRank: 76, partOfSpeech: 'verb', exampleJapanese: '会社で働きます', exampleEnglish: 'I work at a company', tags: ['work'] },
  { term: '休む', reading: 'やすむ', meaning: 'to rest, to take a break', synonyms: ['rest', 'take a break', 'be absent'], readingSynonyms: ['yasumu'], jlptLevel: 'N5', frequencyRank: 77, partOfSpeech: 'verb', exampleJapanese: '日曜日は休みます', exampleEnglish: 'I rest on Sundays', tags: ['daily-life'] },
  { term: '洗う', reading: 'あらう', meaning: 'to wash', synonyms: ['wash', 'clean'], readingSynonyms: ['arau'], jlptLevel: 'N5', frequencyRank: 78, partOfSpeech: 'verb', exampleJapanese: '手を洗います', exampleEnglish: 'I wash my hands', tags: ['daily-life'] },
  { term: '教える', reading: 'おしえる', meaning: 'to teach, to tell', synonyms: ['teach', 'tell', 'inform'], readingSynonyms: ['oshieru'], jlptLevel: 'N5', frequencyRank: 79, partOfSpeech: 'verb', exampleJapanese: '英語を教えます', exampleEnglish: 'I teach English', tags: ['education'] },
  // Days & time
  { term: '月曜日', reading: 'げつようび', meaning: 'Monday', synonyms: ['Monday', 'Mon'], readingSynonyms: ['getsuyoubi'], jlptLevel: 'N5', frequencyRank: 80, partOfSpeech: 'noun', exampleJapanese: '月曜日に学校があります', exampleEnglish: 'There is school on Monday', tags: ['day', 'time'] },
  { term: '火曜日', reading: 'かようび', meaning: 'Tuesday', synonyms: ['Tuesday', 'Tue'], readingSynonyms: ['kayoubi'], jlptLevel: 'N5', frequencyRank: 81, partOfSpeech: 'noun', exampleJapanese: '火曜日はテストです', exampleEnglish: 'There is a test on Tuesday', tags: ['day', 'time'] },
  { term: '土曜日', reading: 'どようび', meaning: 'Saturday', synonyms: ['Saturday', 'Sat'], readingSynonyms: ['doyoubi'], jlptLevel: 'N5', frequencyRank: 82, partOfSpeech: 'noun', exampleJapanese: '土曜日は休みです', exampleEnglish: 'Saturday is a day off', tags: ['day', 'time'] },
  { term: '日曜日', reading: 'にちようび', meaning: 'Sunday', synonyms: ['Sunday', 'Sun'], readingSynonyms: ['nichiyoubi'], jlptLevel: 'N5', frequencyRank: 83, partOfSpeech: 'noun', exampleJapanese: '日曜日に教会に行きます', exampleEnglish: 'I go to church on Sunday', tags: ['day', 'time'] },
  { term: '今', reading: 'いま', meaning: 'now, right now', synonyms: ['now', 'right now', 'currently'], readingSynonyms: ['ima'], jlptLevel: 'N5', frequencyRank: 84, partOfSpeech: 'noun', exampleJapanese: '今何時ですか', exampleEnglish: 'What time is it now?', tags: ['time'] },
  { term: '午前', reading: 'ごぜん', meaning: 'morning, AM', synonyms: ['AM', 'morning', 'before noon'], readingSynonyms: ['gozen'], jlptLevel: 'N5', frequencyRank: 85, partOfSpeech: 'noun', exampleJapanese: '午前10時に会いましょう', exampleEnglish: 'Let\'s meet at 10 AM', tags: ['time'] },
  { term: '午後', reading: 'ごご', meaning: 'afternoon, PM', synonyms: ['PM', 'afternoon', 'after noon'], readingSynonyms: ['gogo'], jlptLevel: 'N5', frequencyRank: 86, partOfSpeech: 'noun', exampleJapanese: '午後3時に来てください', exampleEnglish: 'Please come at 3 PM', tags: ['time'] },
  // Places
  { term: '家', reading: 'いえ', meaning: 'house, home', synonyms: ['house', 'home'], readingSynonyms: ['ie', 'uchi'], jlptLevel: 'N5', frequencyRank: 87, partOfSpeech: 'noun', exampleJapanese: '家に帰ります', exampleEnglish: 'I go home', tags: ['place'] },
  { term: '部屋', reading: 'へや', meaning: 'room', synonyms: ['room'], readingSynonyms: ['heya'], jlptLevel: 'N5', frequencyRank: 88, partOfSpeech: 'noun', exampleJapanese: '部屋が広いです', exampleEnglish: 'The room is spacious', tags: ['place'] },
  { term: '公園', reading: 'こうえん', meaning: 'park', synonyms: ['park'], readingSynonyms: ['kouen'], jlptLevel: 'N5', frequencyRank: 89, partOfSpeech: 'noun', exampleJapanese: '公園で遊びます', exampleEnglish: 'I play at the park', tags: ['place'] },
  { term: 'レストラン', reading: 'れすとらん', meaning: 'restaurant', synonyms: ['restaurant'], readingSynonyms: ['resutoran'], jlptLevel: 'N5', frequencyRank: 90, partOfSpeech: 'noun', exampleJapanese: 'レストランで食べます', exampleEnglish: 'I eat at a restaurant', tags: ['place', 'food'] },
  // Numbers
  { term: '一', reading: 'いち', meaning: 'one (1)', synonyms: ['1', 'one'], readingSynonyms: ['ichi'], jlptLevel: 'N5', frequencyRank: 91, partOfSpeech: 'noun', tags: ['number'] },
  { term: '二', reading: 'に', meaning: 'two (2)', synonyms: ['2', 'two'], readingSynonyms: ['ni'], jlptLevel: 'N5', frequencyRank: 92, partOfSpeech: 'noun', tags: ['number'] },
  { term: '三', reading: 'さん', meaning: 'three (3)', synonyms: ['3', 'three'], readingSynonyms: ['san'], jlptLevel: 'N5', frequencyRank: 93, partOfSpeech: 'noun', tags: ['number'] },
  { term: '百', reading: 'ひゃく', meaning: 'one hundred (100)', synonyms: ['100', 'hundred'], readingSynonyms: ['hyaku'], jlptLevel: 'N5', frequencyRank: 94, partOfSpeech: 'noun', tags: ['number'] },
  { term: '千', reading: 'せん', meaning: 'one thousand (1000)', synonyms: ['1000', 'thousand'], readingSynonyms: ['sen'], jlptLevel: 'N5', frequencyRank: 95, partOfSpeech: 'noun', tags: ['number'] },
  // Additional adjectives
  { term: '長い', reading: 'ながい', meaning: 'long', synonyms: ['long'], readingSynonyms: ['nagai'], jlptLevel: 'N5', frequencyRank: 96, partOfSpeech: 'adjective', exampleJapanese: '長い道', exampleEnglish: 'A long road', tags: ['size', 'description'] },
  { term: '短い', reading: 'みじかい', meaning: 'short', synonyms: ['short', 'brief'], readingSynonyms: ['mijikai'], jlptLevel: 'N5', frequencyRank: 97, partOfSpeech: 'adjective', exampleJapanese: '短い時間', exampleEnglish: 'A short time', tags: ['size', 'description'] },
  { term: '多い', reading: 'おおい', meaning: 'many, a lot', synonyms: ['many', 'a lot', 'numerous'], readingSynonyms: ['ooi'], jlptLevel: 'N5', frequencyRank: 98, partOfSpeech: 'adjective', exampleJapanese: '人が多いです', exampleEnglish: 'There are many people', tags: ['quantity'] },
  { term: '少ない', reading: 'すくない', meaning: 'few, a little', synonyms: ['few', 'a little', 'scarce'], readingSynonyms: ['sukunai'], jlptLevel: 'N5', frequencyRank: 99, partOfSpeech: 'adjective', exampleJapanese: '時間が少ないです', exampleEnglish: 'There is little time', tags: ['quantity'] },
  { term: '好き', reading: 'すき', meaning: 'like, favorite', synonyms: ['like', 'fond of', 'love'], readingSynonyms: ['suki'], jlptLevel: 'N5', frequencyRank: 100, partOfSpeech: 'na-adjective', exampleJapanese: '日本語が好きです', exampleEnglish: 'I like Japanese', tags: ['emotion', 'preference'] },
];

// Sample N5 grammar points
const N5_GRAMMAR = [
  {
    pattern: 'です',
    meaning: 'is, am, are (polite copula)',
    jlptLevel: 'N5',
    order: 1,
    explanation: 'です is the polite form of the copula, used to link a subject to a noun or adjective. It is equivalent to "is/am/are" in English.',
    formation: 'Noun + です\nな-adjective + です',
    examples: [
      { japanese: '私は学生です。', reading: 'わたしはがくせいです。', english: 'I am a student.' },
      { japanese: 'これは本です。', reading: 'これはほんです。', english: 'This is a book.' },
    ],
    tags: ['copula', 'polite'],
    notes: 'The plain form equivalent is だ (da).',
  },
  {
    pattern: 'ます',
    meaning: 'polite verb ending',
    jlptLevel: 'N5',
    order: 2,
    explanation: 'ます is the polite verb ending used in formal situations. It attaches to the verb stem.',
    formation: 'Verb stem + ます',
    examples: [
      { japanese: '食べます', reading: 'たべます', english: 'eat (polite)' },
      { japanese: '日本語を勉強します。', reading: 'にほんごをべんきょうします。', english: 'I study Japanese.' },
    ],
    tags: ['verb', 'polite'],
    notes: 'ません is the negative form, ました is past tense.',
  },
  {
    pattern: 'は (topic marker)',
    meaning: 'as for, speaking of (topic marker)',
    jlptLevel: 'N5',
    order: 3,
    explanation: 'は marks the topic of a sentence - what you are talking about. It is pronounced "wa" when used as a particle.',
    formation: 'Noun + は',
    examples: [
      { japanese: '私は日本人です。', reading: 'わたしはにほんじんです。', english: 'I am Japanese.' },
      { japanese: '今日は暑いです。', reading: 'きょうはあついです。', english: 'Today is hot.' },
    ],
    tags: ['particle', 'topic'],
    relatedPatterns: ['が (subject marker)'],
  },
  {
    pattern: 'を (object marker)',
    meaning: 'object marker',
    jlptLevel: 'N5',
    order: 4,
    explanation: 'を marks the direct object of a verb - the thing that the action is done to.',
    formation: 'Noun + を + Verb',
    examples: [
      { japanese: '水を飲みます。', reading: 'みずをのみます。', english: 'I drink water.' },
      { japanese: '本を読みます。', reading: 'ほんをよみます。', english: 'I read a book.' },
    ],
    tags: ['particle', 'object'],
  },
  {
    pattern: 'に (location/time)',
    meaning: 'at, in, on, to (location/time marker)',
    jlptLevel: 'N5',
    order: 5,
    explanation: 'に indicates a specific point in time, location, or destination.',
    formation: 'Time/Place + に',
    examples: [
      { japanese: '7時に起きます。', reading: 'しちじにおきます。', english: 'I wake up at 7 o\'clock.' },
      { japanese: '東京に行きます。', reading: 'とうきょうにいきます。', english: 'I go to Tokyo.' },
    ],
    tags: ['particle', 'location', 'time'],
    relatedPatterns: ['へ (direction)', 'で (location of action)'],
  },
  {
    pattern: 'で (location of action)',
    meaning: 'at, in (location where action takes place)',
    jlptLevel: 'N5',
    order: 6,
    explanation: 'で marks the location where an action takes place, or the means/method by which something is done.',
    formation: 'Place + で + Verb',
    examples: [
      { japanese: '学校で勉強します。', reading: 'がっこうでべんきょうします。', english: 'I study at school.' },
      { japanese: '電車で行きます。', reading: 'でんしゃでいきます。', english: 'I go by train.' },
    ],
    tags: ['particle', 'location', 'means'],
  },
  {
    pattern: 'と (and, with)',
    meaning: 'and, with',
    jlptLevel: 'N5',
    order: 7,
    explanation: 'と connects nouns (and) or indicates accompaniment (with).',
    formation: 'Noun + と + Noun\nPerson + と + Verb',
    examples: [
      { japanese: 'りんごとみかん', reading: 'りんごとみかん', english: 'apples and oranges' },
      { japanese: '友達と映画を見ます。', reading: 'ともだちとえいがをみます。', english: 'I watch a movie with a friend.' },
    ],
    tags: ['particle', 'conjunction'],
  },
  {
    pattern: 'か (question)',
    meaning: 'question marker',
    jlptLevel: 'N5',
    order: 8,
    explanation: 'か at the end of a sentence turns it into a question.',
    formation: 'Statement + か',
    examples: [
      { japanese: 'これは何ですか。', reading: 'これはなんですか。', english: 'What is this?' },
      { japanese: '日本語がわかりますか。', reading: 'にほんごがわかりますか。', english: 'Do you understand Japanese?' },
    ],
    tags: ['particle', 'question'],
  },
  {
    pattern: 'ない (negative)',
    meaning: 'not, negative verb form',
    jlptLevel: 'N5',
    order: 9,
    explanation: 'ない is the plain negative form of verbs.',
    formation: 'Verb (negative stem) + ない',
    examples: [
      { japanese: '食べない', reading: 'たべない', english: 'don\'t eat' },
      { japanese: '分からない', reading: 'わからない', english: 'don\'t understand' },
    ],
    tags: ['verb', 'negative', 'plain'],
    relatedPatterns: ['ません (polite negative)'],
  },
  {
    pattern: 'たい (want to)',
    meaning: 'want to',
    jlptLevel: 'N5',
    order: 10,
    explanation: 'たい expresses the speaker\'s desire to do something.',
    formation: 'Verb stem + たい',
    examples: [
      { japanese: '日本に行きたい。', reading: 'にほんにいきたい。', english: 'I want to go to Japan.' },
      { japanese: 'ラーメンが食べたい。', reading: 'らーめんがたべたい。', english: 'I want to eat ramen.' },
    ],
    tags: ['verb', 'desire'],
    notes: 'This is only used for the speaker\'s own desires. For others, use たがっている.',
  },
  {
    pattern: 'が (subject marker)',
    meaning: 'subject marker',
    jlptLevel: 'N5',
    order: 11,
    explanation: 'が marks the grammatical subject. It emphasizes who or what performs the action, and is required after question words like 何、誰、どれ.',
    formation: 'Noun + が',
    examples: [
      { japanese: '猫がいます。', reading: 'ねこがいます。', english: 'There is a cat.' },
      { japanese: '誰が来ますか。', reading: 'だれがきますか。', english: 'Who is coming?' },
    ],
    tags: ['particle', 'subject'],
    relatedPatterns: ['は (topic marker)'],
    notes: 'は introduces topics (often known info), が marks subjects (often new info or emphasis).',
  },
  {
    pattern: 'の (possessive)',
    meaning: 'possessive, of',
    jlptLevel: 'N5',
    order: 12,
    explanation: 'の connects two nouns to show possession or a relationship between them.',
    formation: 'Noun A + の + Noun B',
    examples: [
      { japanese: '私の本', reading: 'わたしのほん', english: 'my book' },
      { japanese: '日本語の先生', reading: 'にほんごのせんせい', english: 'Japanese teacher' },
    ],
    tags: ['particle', 'possessive'],
  },
  {
    pattern: 'も (also, too)',
    meaning: 'also, too, as well',
    jlptLevel: 'N5',
    order: 13,
    explanation: 'も replaces は or が to mean "also" or "too". It adds something to an existing statement.',
    formation: 'Noun + も',
    examples: [
      { japanese: '私も学生です。', reading: 'わたしもがくせいです。', english: 'I am also a student.' },
      { japanese: 'これもいいです。', reading: 'これもいいです。', english: 'This is good too.' },
    ],
    tags: ['particle', 'additive'],
  },
  {
    pattern: 'から (because / from)',
    meaning: 'because; from',
    jlptLevel: 'N5',
    order: 14,
    explanation: 'から has two main uses: (1) to give a reason (because), and (2) to mark the starting point of time or place (from).',
    formation: 'Reason clause + から\nPlace/Time + から',
    examples: [
      { japanese: '眠いから寝ます。', reading: 'ねむいからねます。', english: 'I\'ll sleep because I\'m sleepy.' },
      { japanese: '9時から授業があります。', reading: 'くじからじゅぎょうがあります。', english: 'Class starts from 9 o\'clock.' },
    ],
    tags: ['conjunction', 'reason', 'particle'],
  },
  {
    pattern: 'て形 (te-form)',
    meaning: 'te-form (connecting actions)',
    jlptLevel: 'N5',
    order: 15,
    explanation: 'The te-form connects multiple actions in sequence, makes requests, and is used in many grammar patterns.',
    formation: 'Verb → te-form (rules vary by verb group)',
    examples: [
      { japanese: '手を洗って食べます。', reading: 'てをあらってたべます。', english: 'I wash my hands and eat.' },
      { japanese: '電車に乗って学校に行きます。', reading: 'でんしゃにのってがっこうにいきます。', english: 'I take the train to school.' },
    ],
    tags: ['verb', 'te-form', 'sequence'],
    notes: 'The te-form is essential for many patterns: ている, てください, てもいい, etc.',
  },
  {
    pattern: 'ている (ongoing state / action)',
    meaning: 'is doing, have done (resultant state)',
    jlptLevel: 'N5',
    order: 16,
    explanation: 'ている has two main uses: (1) an action currently in progress, and (2) a resultant state from a completed action.',
    formation: 'Verb (te-form) + いる',
    examples: [
      { japanese: '今、勉強しています。', reading: 'いま、べんきょうしています。', english: 'I am studying now.' },
      { japanese: '結婚しています。', reading: 'けっこんしています。', english: 'I am married.' },
    ],
    tags: ['verb', 'progressive', 'te-form'],
  },
  {
    pattern: 'てください (please do)',
    meaning: 'please do ~',
    jlptLevel: 'N5',
    order: 17,
    explanation: 'てください is used to make polite requests.',
    formation: 'Verb (te-form) + ください',
    examples: [
      { japanese: 'ここに座ってください。', reading: 'ここにすわってください。', english: 'Please sit here.' },
      { japanese: '名前を書いてください。', reading: 'なまえをかいてください。', english: 'Please write your name.' },
    ],
    tags: ['verb', 'request', 'te-form', 'polite'],
    relatedPatterns: ['てもいいですか (may I)'],
  },
  {
    pattern: 'ことができる (can do)',
    meaning: 'can, be able to',
    jlptLevel: 'N5',
    order: 18,
    explanation: 'ことができる expresses ability to do something.',
    formation: 'Verb (dictionary form) + ことができる',
    examples: [
      { japanese: '日本語を話すことができます。', reading: 'にほんごをはなすことができます。', english: 'I can speak Japanese.' },
      { japanese: '泳ぐことができません。', reading: 'およぐことができません。', english: 'I cannot swim.' },
    ],
    tags: ['verb', 'ability', 'potential'],
    relatedPatterns: ['られる (potential form)'],
  },
  {
    pattern: 'より (comparison)',
    meaning: 'than, more than',
    jlptLevel: 'N5',
    order: 19,
    explanation: 'より is used for comparisons, meaning "than". The item after より is what you are comparing against.',
    formation: 'Noun A + は + Noun B + より + adjective',
    examples: [
      { japanese: '東京は大阪より大きいです。', reading: 'とうきょうはおおさかよりおおきいです。', english: 'Tokyo is bigger than Osaka.' },
      { japanese: '電車よりバスが速いです。', reading: 'でんしゃよりばすがはやいです。', english: 'The bus is faster than the train.' },
    ],
    tags: ['particle', 'comparison'],
  },
  {
    pattern: '〜時 (time)',
    meaning: 'at ~ o\'clock / when ~',
    jlptLevel: 'N5',
    order: 20,
    explanation: '時 (ji) is used to express specific clock times. It follows the number.',
    formation: 'Number + 時',
    examples: [
      { japanese: '7時に起きます。', reading: 'しちじにおきます。', english: 'I wake up at 7 o\'clock.' },
      { japanese: '何時ですか。', reading: 'なんじですか。', english: 'What time is it?' },
    ],
    tags: ['time', 'counter'],
  },
];

async function seedVocabulary() {
  console.log('Seeding vocabulary data...');
  
  const batch = db.batch();
  
  for (const vocab of N5_VOCABULARY) {
    const docRef = db.collection('vocabularies').doc();
    batch.set(docRef, {
      ...vocab,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
  }
  
  await batch.commit();
  console.log(`Seeded ${N5_VOCABULARY.length} vocabulary items`);
}

async function seedGrammar() {
  console.log('Seeding grammar data...');
  
  const batch = db.batch();
  
  for (const grammar of N5_GRAMMAR) {
    const docRef = db.collection('grammarPoints').doc();
    batch.set(docRef, {
      ...grammar,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
  }
  
  await batch.commit();
  console.log(`Seeded ${N5_GRAMMAR.length} grammar points`);
}

async function main() {
  try {
    await seedVocabulary();
    await seedGrammar();
    console.log('Seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
}

main();

